apiVersion: v1
kind: Service
metadata:
  name: bootcamp-python
  namespace: prod1
spec:
  selector:
    app: bootcamp-python
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30301
    protocol: TCP
